FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml .npmrc ./
RUN pnpm install --prod --frozen-lockfile

COPY scripts ./scripts
COPY server ./server

ENV API_HOST=0.0.0.0
ENV API_PORT=4000
ENV NODE_ENV=production

EXPOSE 4000

CMD ["pnpm", "api"]
