FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

COPY scripts ./scripts
COPY server ./server
COPY statistic.xls ./statistic.xls

ENV API_HOST=0.0.0.0
ENV API_PORT=4000

EXPOSE 4000

CMD ["pnpm", "api"]
