/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as PosTableRouteImport } from './routes/pos-table'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as AppealsRouteImport } from './routes/appeals'
import { Route as IndexRouteImport } from './routes/index'

const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const PosTableRoute = PosTableRouteImport.update({
  id: '/pos-table',
  path: '/pos-table',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealsRoute = AppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/experiments': typeof ExperimentsRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/pos-table': typeof PosTableRoute
  '/references': typeof ReferencesRoute
  '/slides': typeof SlidesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/experiments': typeof ExperimentsRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/pos-table': typeof PosTableRoute
  '/references': typeof ReferencesRoute
  '/slides': typeof SlidesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/experiments': typeof ExperimentsRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/pos-table': typeof PosTableRoute
  '/references': typeof ReferencesRoute
  '/slides': typeof SlidesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appeals'
    | '/experiments'
    | '/login'
    | '/pos'
    | '/pos-table'
    | '/references'
    | '/slides'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appeals'
    | '/experiments'
    | '/login'
    | '/pos'
    | '/pos-table'
    | '/references'
    | '/slides'
  id:
    | '__root__'
    | '/'
    | '/appeals'
    | '/experiments'
    | '/login'
    | '/pos'
    | '/pos-table'
    | '/references'
    | '/slides'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppealsRoute: typeof AppealsRoute
  ExperimentsRoute: typeof ExperimentsRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRoute
  PosTableRoute: typeof PosTableRoute
  ReferencesRoute: typeof ReferencesRoute
  SlidesRoute: typeof SlidesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-table': {
      id: '/pos-table'
      path: '/pos-table'
      fullPath: '/pos-table'
      preLoaderRoute: typeof PosTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeals': {
      id: '/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppealsRoute: AppealsRoute,
  ExperimentsRoute: ExperimentsRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRoute,
  PosTableRoute: PosTableRoute,
  ReferencesRoute: ReferencesRoute,
  SlidesRoute: SlidesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
